name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  draft-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: dist

      - name: Zip build artifact
        run: (cd dist && zip -r ../site-dist.zip .)

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: site-dist.zip
