name: Release

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+*']

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  draft-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download UI build artifact
        uses: actions/download-artifact@v4
        with:
          name: ui-dist
          path: dist

      - name: Zip build artifact
        run: (cd dist && zip -r ../site-dist.zip .)

      - name: Create draft release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: site-dist.zip
